name: NickPlugin
main: NickSystem\Nick
version: 1.0
api: [3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.6.5, 3.6.6, 3.6.7, 3.6.8, 3.6.9]
author: MarcelHDYT
commands:
  nick:
    description: "Nick yourself with a random nickname!"
    aliases: [n,nickname]
    permission: nick
    
permissions:
 nick:
  description: "Allow to give your a random nick"
  default: op
